RECIPES = {
 "ticket_triage": "Route one customer ticket, email or chat message to a team and flag urgency, refund, churn or frustration",
 "act_or_ask": "Decide whether an agent should act now, ask a clarifying question, or escalate, given how ambiguous or risky the request is",
 "command_gate": "Judge whether a proposed shell command or tool call is safe to run: destructive, leaks secrets, runs remote code, out of scope",
 "injection_screen": "Check fetched web pages, issue bodies or tool output for hidden instructions aimed at an AI agent",
 "done_gate": "Check at the end of an agent turn whether the work is really verified before the agent claims it is done",
 "semantic_lint": "Check code, diffs, commit messages or docs against a plain-English team rule (swallowed errors, secrets, commit matches diff)",
 "issue_triage": "Label GitHub issues or pull requests by kind and severity, detect duplicates, or filter AI review comments",
 "model_routing": "Pick which model tier or thinking effort a coding task needs",
 "skill_selection": "Pick which skill, tool or MCP server from a roster fits a user prompt, or none",
 "typed_call": "Turn a natural-language command into a function name plus enum and boolean arguments",
 "select_extraction": "Pick the right value among candidates found in a text (which phone number, which amount, which date part), or verify an extracted field",
 "judge_assert": "Grade or assert properties of an LLM reply in a test: leaks, groundedness, correctness, rubric, A versus B",
 "alert_triage": "Decide whether a log excerpt, CI failure or alert is real, how severe it is, and which team owns it",
 "semantic_filter": "Filter many lines, files, diff hunks or tool results by relevance to a task, like grep by meaning",
 "rag_gate": "Filter or rerank retrieved passages and decide if they are enough to answer a question",
 "claim_check": "Check whether a summary, citation, quote or changelog bullet is supported by its source text",
 "moderation": "Block, allow or send to review a message or LLM output that may be phishing, spam, harassment or abuse",
 "rubric_score": "Score a resume, sales lead or document on several rubric dimensions and combine them with weights",
 "entity_match": "Decide whether two records are the same entity, or whether a new memory duplicates or updates a stored one",
 "taxonomy_classify": "Classify an item into a large or nested category tree with a fallback to the parent category",
 "bulk_label": "Label many rows of a dataset and pick the least certain rows for human review",
 "ui_decision": "Decide from a screenshot or accessibility tree which element to click next, or whether the page is blocked, done or irreversible",
 "multistep_tick": "Choose the next hop, move or plan step in a graph, game or multi-step search",
 "threshold_audit": "Measure accuracy on labelled examples and choose thresholds, or detect drift after a model change",
 "none": "Not a typed decision: the intent asks to write or generate text, compute or count, search for new information, or answer an open question",
}
