"""Package-data library (spec 2.18): batch templates, question patterns, authoring guide. Read once, no network.
Data is generated by scripts/gen_library.py from the verified section 5 cases."""
from __future__ import annotations

import json
from functools import lru_cache
from importlib import resources


def _read(name: str) -> str:
    return resources.files("openjev_mcp").joinpath("data", name).read_text(encoding="utf-8")


@lru_cache(maxsize=None)
def _templates() -> dict[str, dict]:
    return json.loads(_read("templates.json"))


@lru_cache(maxsize=None)
def _patterns() -> dict[str, dict]:
    return json.loads(_read("patterns.json"))


def template_ids() -> list[str]:
    return sorted(_templates())


def templates_index() -> list[dict]:
    return [{"id": t["id"], "title": t["title"], "description": t["description"],
             "question_count": len(t["questions"]), "state_count": len(t["states"])}
            for t in (_templates()[i] for i in template_ids())]


def template(id: str) -> dict | None:
    t = _templates().get(id)
    if t is None:
        return None
    return json.loads(json.dumps({k: t[k] for k in ("id", "title", "questions", "options", "states", "source_case")}))


def patterns() -> dict:
    return json.loads(json.dumps(_patterns()))


@lru_cache(maxsize=None)
def guide() -> str:
    return _read("guide_authoring.md")
